version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file pdftotxt.yaml --s3-bucket ravi-pgdcc-artifact-bucket --output-template-file lambdaoutput.yaml --capabilities CAPABILITY_AUTO_EXPAND

artifacts:
  type: zip
  files:
    - pdftotxt.yaml
    - lambdaoutput.yaml
